general:
  executersCount: 0
  cliOverRemoting: false
  changeWorkspaceDir: true

security:
  realm: jenkins_database
  adminPassword: admin
  permissions:
    authenticated:
      - hudson.model.Hudson.Read
      - hudson.model.Item.Read
      - hudson.model.Item.Discover
      - hudson.model.Item.Cancel
    test-group:
      - hudson.model.Computer.Build
      - hudson.model.Computer.Configure
      - hudson.model.Computer.Connect
      - hudson.model.Computer.Create
      - hudson.model.Computer.Delete
      - hudson.model.Computer.Disconnect
      - hudson.model.Computer.Provision
      - hudson.model.Hudson.Administer
      - hudson.model.Hudson.Read
      - hudson.model.Item.Build
      - hudson.model.Item.Cancel
      - hudson.model.Item.Configure
      - hudson.model.Item.Create
      - hudson.model.Item.Delete
      - hudson.model.Item.Discover
      - hudson.model.Item.Move
      - hudson.model.Item.Read
      - hudson.model.Item.ViewStatus
      - hudson.model.Item.Workspace
      - hudson.model.Run.Delete
      - hudson.model.Run.Replay
      - hudson.model.Run.Update
      - hudson.model.View.Configure
      - hudson.model.View.Create
      - hudson.model.View.Delete
      - hudson.model.View.Read
      - hudson.scm.SCM.Tag
      - org.jenkins.plugins.lockableresources.LockableResourcesManager.Reserve
      - org.jenkins.plugins.lockableresources.LockableResourcesManager.Unlock
      - org.jfrog.hudson.ArtifactoryPlugin.Promote
      - org.jfrog.hudson.ArtifactoryPlugin.PushToBintray
      - org.jfrog.hudson.ArtifactoryPlugin.Release      
      - com.cloudbees.plugins.credentials.CredentialsProvider.Create
      - com.cloudbees.plugins.credentials.CredentialsProvider.Delete
      - com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains
      - com.cloudbees.plugins.credentials.CredentialsProvider.Update
      - com.cloudbees.plugins.credentials.CredentialsProvider.View

tools:
  XVFB:
    type: xvfb
    home: /usr/bin
  JDK7:
    type: jdk
    home: /usr/lib/jvm/java-1.7-openjdk
  JDK8:
    type: jdk
    home: /usr/lib/jvm/java-1.8-openjdk
  MAVEN-3.5.0:
    type: maven
    home: /usr/share/apache-maven-3.5.0
  ANT-1.9.4:
    type: ant
    home: /usr/share/apache-ant-1.9.4
  GRADLE-4.2.1:
    type: gradle
    home: /usr/share/gradle-4.2.1

credentials:
  slack:
    type: text
    text: abcdefg
  hipchat:
    type: text
    text: abcdefg
  awscred:
    type: aws
    access_key: xxxx
    secret_access_key: yyyy
  gituserpass:
    type: userpass
    username: user
    password: password1234
  gitsshkey:
    type: sshkey
    description: git-ssh-key
    username: user
    passphrase: password1234
    privatekey: |
      -----BEGIN RSA PRIVATE KEY-----
      Proc-Type: 4,ENCRYPTED
      DEK-Info: AES-128-CBC,B1615A0CA4F11333D058A5A9C4D0144E

      wxr6qxA/gcj+Bf1he0YRaqH2HbvHXIshrXTFq7oet5OeF1oaX4yyejotI9oPXvvM
      X9jzLpPwhdpriuFKJKr9jc+1rto/71QExTYEaAWwfYi1EVb1ERGmG4DMANqBKssO
      FTn01t4wew3d6DPcAIwFBT7gvlJfg0poCxae1fhsXGijMy2YryiU+BcV0BYsM6Lj
      VAfn9+djoxPKTv3wPFZPXVrzSkWG8IFUcLBIKE6hf3xxwV5FPHDSegAnwTBV9sVB
      BkVfAHDkzecEtK3iHqa9QUsW014TTLZ7Rbbzh6mskrGxgjgDXXjbdEYbJDtSES6E
      d2o1nXqJEsDdUrSWAoaViR052KyW8f8n//LEjI1a6aveOQWoWXgPwD9jnp5cPrGv
      mWGrZmhWLh0rx61qG+bBVEfbGmLmbi74jxq1/6vaAF4ChtfBks2mpOMMOKf+bKar
      w1laJKgwFRWO7iYql9dHzny2GXy4z6hjD5g3omEdFyWh3GSW8NNkXyojml7tlIa6
      ln286//PSmN0dLZptULAr8A4Bp+aGgybnla7H2F5/s2mGc39MrodFPFbpjp50d4R
      2x4uV4ofVvVExv5wWSdQ60o7trSvBWqwu4MDm2yWCxUiay8I8EF2iM0etutlWm5N
      V9aD8TTC5zHLbwY7YI0OvOXyCWgI5CW1tTsnoDxR1H0aDByuSL+Q+8I5gxRKdJlb
      fYZ683g8AuTkKilHQ6KINAAUuvMvgSWzOa/BU9L7Xqn99w2WgdheLMkdp6O4dJX4
      f4vFTzms+tBVXwqybac/8HZ4uW163pgnBpH2bVFi7/qyd8sl8TYAODN70R2oLv3c
      HBjzI/078G9B4WkpL99FK9cWsfCleIM+HIGeQ9jPDK/hzAhlKIIQxzIaomhcRZlW
      Oc3+zlioBuQSBVtf1UJMrCFSfr9Gq+lbhsD5k8bscU38d5R8EHDGvicpr/KIwjGn
      piNmO7Nz2KcJaLUX6D1oG0p4ioan7js27eBGVnur73hNySbFycwiTGdZkp1CHM7D
      OH2iOMibQGMGYWoci/SoIOgp54Meq4WkEpV5wwr6aCuTzsgnVJXVuMmBk8dnvyat
      EKflp+2kKCj9uPo/QUoozNAuNzyDJU95E8ZfLyT5G9GCQtlf2EnrFZIeQ040xBQC
      6vGQLodjxIG1X8ejDv69FIW66qyofAWVuwCO6wuCWEdLLZrNNhjyPCnnxv5Kw8oC
      nB8/YDntqKg2GqpDu4s0bzAt0CPbMQydvD5x4AWKYCm4HQIF3qX544yUKd9vuO3l
      5t8JE8l4ETGMieKFpE9YiVbobye8iNRyIYVBuvlk4lq+xifw7i3Crmr/+KB+2ABZ
      8TshgEjw8G7TR7qZjZGONCBJ6ozUNR5ipUANc81AA3AUGilBeC4lLUcvatsixtWz
      6BDHwOYfLbfm8YIxDELMt13f++sxKoed4EjFJu+JIjEZlRomPf9pZEmZwTRVASsc
      CbwJjRc022b7HIsetGBYu76KK/Fs25D5JTZjQ3ylMKwhBjrOT7d8Xm90/6eg4hvE
      4c9bdLH+2Xuc6qv/oBoFzVd19c3DiVfns2/5BohfG+pbNwZUVR1vjP/BVDgwDBc+
      -----END RSA PRIVATE KEY-----

clouds:
  ecs-cloud:
    type: ecs
    credentialsId: ''
    cluster: 'arn:ssss'
    region: eu-west-1
    # jenkinsUrl: 'xxx'
    connectTimeout: 0
    templates:
      - name: ecsSlave
        image: jenkinsci/jnlp-slave:latest
        labels:
          - ecs-slave
        remoteFs: /home/jenkins
        jvmArgs: -Xmx1g
        memoryReservation: 2048
        cpu: 1024
        volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
        environment:
          XXX: xxx

  kube-cloud:
    type: kubernetes
    serverUrl: xxx
    namespace: yyy
    # jenkinsUrl: xxx
    connectTimeout: 0
    templates:
      - name: kubeslave
        image: jenkinsci/jnlp-slave:latest
        labels:
          - kubeslave
        remoteFs: /home/jenkins
        jvmArgs: -Xmx1g
        volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
        environment:
          XXX: xxx

  # docker-cloud:
  #   type: docker
  #   serverUrl: unix:///var/run/docker.sock
  #   templates:
  #     - image: jenkinsci/ssh-slave:latest
  #       labels:
  #         - docker
  #         - docker-slave
  #       remoteFs: /home/jenkins
  #       jvmArgs: -Xmx1g
  #       memory: 2048
  #       cpu: 1024
  #       volumes:
  #         - '/var/run/docker.sock:/var/run/docker.sock'
  #       environment:
  #         XXX: xxx

notifiers:
  mail:
    host: xxx.mydomain.com
    port: 25
    authUser: test
    autPassword: test
    replyToAddress: no-reply@mydomain.com
    defaultSuffix: '@mydomain.com'
    useSsl: true
    charset: UTF-8
  hipchat:
    server: my.api.hipchat.com
    room: JenkinsNotificationRoom
    sendAs: TestSendAs
    v2Enabled: true
    credentialId: hipchat
  slack:
    credentialId: slack
    teamDomain: teamDoamin
    botUser: true
    room: TestRoom
    baseUrl: http://localhost:8080/
    sendAs: JenkinsSlack

pipeline_libraries:
  my-library:
    source:
      remote: git@github.com:odavid/jenkins-docker.git
      credentialsId: gitsshkey
    defaultVersion: master
    implicit: false
    allowVersionOverride: true
    includeInChangesets: true


script_approval:
  approvals:
    - field hudson.model.Queue$Item task
    - method groovy.lang.Binding getVariable java.lang.String
    - method groovy.lang.Binding getVariables
    - method groovy.lang.Binding hasVariable java.lang.String
    - method hudson.model.AbstractCIBase getQueue
    - method hudson.model.Actionable getAction java.lang.Class
    - method hudson.model.Actionable replaceAction hudson.model.Action
    - method hudson.model.Cause$UpstreamCause getUpstreamProject
    - method hudson.model.Item getFullName
    - method hudson.model.Job getBuildByNumber int
    - method hudson.model.Job getLastBuild
    - method hudson.model.Job getLastCompletedBuild
    - method hudson.model.Job getLastSuccessfulBuild
    - method hudson.model.Queue getItems
    - method hudson.model.Queue$Item doCancelQueue
    - method hudson.model.Run getArtifacts
    - method hudson.model.Run getCauses
    - method hudson.model.Run getNumber
    - method hudson.model.Run getPreviousBuild
    - method hudson.model.Run keepLog
    - method hudson.model.Run setDisplayName java.lang.String
    - method hudson.model.Saveable save
    - method hudson.tasks.junit.ClassResult getClassName
    - method hudson.tasks.junit.TestObject getDuration
    - method hudson.tasks.junit.TestObject getName
    - method hudson.tasks.junit.TestObject getParent
    - method hudson.tasks.test.AbstractTestResultAction getFailCount
    - method hudson.tasks.test.AbstractTestResultAction getFailedTests
    - method hudson.tasks.test.AbstractTestResultAction getResult
    - method hudson.tasks.test.TabulatedResult getChildren
    - method hudson.tasks.test.TestObject getFullName
    - method hudson.tasks.test.TestResult getFailedTests
    - method java.io.File getParent
    - method java.io.File toURI
    - method java.lang.Class getClassLoader
    - method java.lang.Class isInstance java.lang.Object
    - method java.lang.String substring int
    - method java.lang.Throwable getMessage
    - method java.net.URI toURL
    - method java.net.URLClassLoader addURL java.net.URL
    - method java.util.Map size
    - method java.util.Map values
    - method java.util.Queue poll
    - method jenkins.model.Jenkins getItemByFullName java.lang.String java.lang.Class
    - method org.jenkinsci.plugins.workflow.steps.FlowInterruptedException getCauses
    - method org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder$BadgeManager createSummary java.lang.String
    - method org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildSummaryAction appendText java.lang.String boolean
    - method org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildSummaryAction appendText java.lang.String boolean boolean boolean java.lang.String
    - new hudson.plugins.copyartifact.SpecificBuildSelector java.lang.String
    - new hudson.tasks.junit.TestResult
    - new hudson.tasks.junit.TestResultAction hudson.tasks.junit.TestResult hudson.model.BuildListener
    - new java.lang.RuntimeException java.lang.String
    - new java.util.ArrayList int
    - new java.util.PriorityQueue int java.util.Comparator
    - new org.jenkinsci.plugins.docker.commons.credentials.DockerRegistryEndpoint java.lang.String java.lang.String
    - staticField hudson.model.Result SUCCESS
    - staticField java.lang.Long MAX_VALUE
    - staticField java.lang.Long MIN_VALUE
    - staticMethod groovy.sql.Sql newInstance java.util.Map
    - staticMethod java.lang.Class forName java.lang.String
    - staticMethod java.lang.Math max int int
    - staticMethod java.lang.Math max long long
    - staticMethod java.lang.Math min int int
    - staticMethod java.lang.Math min long long
    - staticMethod java.lang.Math pow double double
    - staticMethod java.lang.Math sqrt double
    - staticMethod java.util.Calendar getInstance java.util.TimeZone
    - staticMethod java.util.Collections sort java.util.List java.util.Comparator
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getRootLoader java.lang.ClassLoader
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods inject java.util.Collection java.lang.Object groovy.lang.Closure
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods invokeMethod java.lang.Object java.lang.String java.lang.Object
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods plus java.util.Collection java.lang.Iterable
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods plus java.util.Collection java.lang.Object
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods plus java.util.Collection java.util.Collection
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods plus java.util.List java.lang.Object
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods plus java.util.Map java.util.Map
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods plus java.util.Set java.lang.Object
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods println java.lang.Object java.lang.Object
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods readLines java.lang.String
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods sort java.util.Collection groovy.lang.Closure
    - staticMethod org.codehaus.groovy.runtime.ScriptBytecodeAdapter castToType java.lang.Object java.lang.Class
    - staticMethod org.codehaus.groovy.runtime.ScriptBytecodeAdapter isCase java.lang.Object java.lang.Object
    - staticMethod org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder.BadgeManager createSummary java.lang.String