sudo: required

services:
  - docker

script:
  - docker build --rm --force-rm -t odavid/my-bloody-jenkins .

deploy:
  - provider: script
    script: curl --request POST --header Content-Type:application/json --data '{"build":true}' --url ${DOCKER_CLOUD_TRIGGER_URL}
    on:
      branch: master
