version: '2'
services:
  jenkins-master:
    build: ../..
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '.data/jenkins_home:/var/jenkins_home'
      - '.data/jenkins-workspace-home:/jenkins-workspace-home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      JAVA_OPTS_MEM: '-Xmx1g'
      JENKINS_ENV_ADMIN_USER: admin
      JENKINS_ENV_HOST_IP: ${MY_HOST_IP}
      JENKINS_ENV_CONFIG_YAML: |
        security:
          realm: jenkins_database
          adminPassword: admin
        credentials:
          minikube-cert:
            type: cert
            base64: ${MINIKUBE_CERT}
            password: ${MINIKUBE_CERT_PASSWORD}
        tools:
          installations:
            MVN-3.5.0:
              type: maven
              installers:
                - id: '3.5.0'
        clouds:
          kube-cloud:
            type: kubernetes
            serverUrl: https://${MINIKUBE_IP}:${MINIKUBE_PORT}
            skipTlsVerify: true
            credentialsId: minikube-cert
            templates:
              - name: kubeslave
                image: jenkinsci/jnlp-slave:latest
                labels:
                  - kubeslave
                remoteFs: /home/jenkins
                jvmArgs: -Xmx1g
                volumes:
                  - '/var/run/docker.sock:/var/run/docker.sock'
        seed_jobs:
          seed-job:
            source: 
              remote: https://github.com/odavid/my-bloody-jenkins.git
              branch: 'kubernetes-example'
            triggers: 
              pollScm: 'H/2 * * * *'
              periodic: '@hourly'
            pipeline: example/jobs/seed/Jenkinsfile
            executeWhen: always #firstTimeOnly always never
        

